services:
  - type: web
    name: verein-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_SECRET
        sync: false
      - key: AzureConnection
        sync: false